nama=input('Nama                      : ')
nim=input('NIM                       : ')
kelas=input('Kelas Paralel             : ')
ttl=input('Tempat/Tanggal Lahir      : ')
alm=input('Alamat                    : ')
hoby=input('Hobby                     : ')
hp=input('No. HP                    : ')
print('\nNama                      : ', nama)
print('NIM                       : ', nim)
print('Kelas Paralel             : ', kelas)
print('Tempat/Tanggal Lahir      : ', ttl)
print('Alamat                    : ', alm)
print('Hobby                     : ', hoby)
print('No. HP                    : ', hp)